/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practica4_smm;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author rober
 */
public class Lienzo extends javax.swing.JPanel {
    private Point pressedPoint = null;
    private Shape forma = new Line2D.Float();
    private HerramientaDibujo herramienta = HerramientaDibujo.LINE;
    private Color color = Color.BLACK;
    private Boolean relleno = false;

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        
        if (forma != null) {
            g2d.setPaint(color);
            if (relleno) g2d.fill(forma);
            g2d.draw(forma);
        }
    }

    public Shape getForma() {
        return forma;
    }

    public void setForma(Shape forma) {
        this.forma = forma;
    }

    public HerramientaDibujo getHerramienta() {
        return herramienta;
    }

    public void setHerramienta(HerramientaDibujo herramienta) {
        this.herramienta = herramienta;
    }

    public Color getColor() {
        return color;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public Boolean getRelleno() {
        return relleno;
    }

    public void setRelleno(Boolean relleno) {
        this.relleno = relleno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        switch(herramienta){
            case HerramientaDibujo.LINE:
                this.forma = new Line2D.Float(evt.getPoint(), evt.getPoint());
                break;
            case HerramientaDibujo.RECTANGLE:
                this.pressedPoint = evt.getPoint();
                this.forma = new Rectangle2D.Float();
                break;
            case HerramientaDibujo.ELLIPSE:
                this.pressedPoint = evt.getPoint();
                this.forma = new Ellipse2D.Float();
                break;
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        switch(herramienta){
            case HerramientaDibujo.LINE:
                ((Line2D)this.forma).setLine(((Line2D)forma).getP1(), evt.getPoint());
                break;
            case HerramientaDibujo.RECTANGLE:
                ((Rectangle2D)this.forma).setFrameFromDiagonal(this.pressedPoint, evt.getPoint());
                break;
            case HerramientaDibujo.ELLIPSE:
                ((Ellipse2D)this.forma).setFrameFromDiagonal(this.pressedPoint, evt.getPoint());
                break;
        }
        this.repaint();
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
